FROM amazoncorretto:17-alpine
LABEL AUTHOR="Cristian_SknZ"

RUN mkdir /app
COPY ./build/libs/simpleblog-0.0.1-SNAPSHOT.jar /app/simpleblog.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar","/app/simpleblog.jar"]