spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: simpleblog
      database: simpleblog

authentication:
  jwt:
    client-secret: simpleblog-random-secret
    expires: 3600